<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JSApp\Module' => __DIR__ . '/Module.php',
    'JSApp\Controller\IndexController' => __DIR__ . '/src/JSApp/Controller/Pessoa/SaneamentoController.php',
);
