<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DBISmartScore\Module'                        => __DIR__ . '/Module.php',
    'DBISmartScore\Controller\ConsultaController' => __DIR__ . '/src/DBISmartScore/Controller/ConsultaController.php',
);
