<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JSExt\Module'                        => __DIR__ . '/Module.php',
    'JSExt\Controller\IndexController' => __DIR__ . '/src/JSExt/Controller/IndexController.php',
    'JSExtTest\Framework\TestCase'        => __DIR__ . '/tests/JSExt/Framework/TestCase.php',
    'JSExtTest\SampleTest'                => __DIR__ . '/tests/JSExt/SampleTest.php',
);
